version: "3.3"

services:
  frontend-web:
    image: roborregos/frontend-web:1.0
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src
    ports:
      - 3000:3000
    command: bash -c "yarn && yarn start"
    stdin_open: true
