version: '3.3'

services:
  roborregos-web:
    command: bash -c "yarn && yarn start"
    image: roborregos-web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000